language: go

# Compile with the latest OS image (previously 12.04, now 14.04)
# `sudo: required` is the default for repositories enabled before 2015 (we don't need it and it's slower)
dist: trusty
sudo: false

# https://docs.travis-ci.com/user/database-setup/
# Some of the db unit tests require redis on 127.0.0.0:6379
services:
- redis-server

# Compile with go 1.10 (or newer). It takes a long time to install `tip`
go:
  - 1.13.x

# Only compute the build status for PRs in travis
branches:
  only:
    - master

# install step default is `go get ./...`
# script default is `go test ./...`
# (Could include apns-test.sh, but that doesn't have expected output written yet)
script:
  - go build
  - go tool vet -printfuncs debugf,infof,configf,warnf,errorf,alertf,fatalf .
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  # run gometalinter checks from .gometalinter.json
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
